# Generated by Django 4.1.3 on 2022-11-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default='1970-01-01', verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(default='', max_length=255, verbose_name='ФИО'),
        ),
    ]
