# Generated by Django 4.1.3 on 2022-11-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_birth_date_customuser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('A', 'Администратор'), ('B', 'Бухгалтер'), ('D', 'Водитель')], default='D', max_length=1, verbose_name='Должность'),
        ),
    ]
