# Generated by Django 3.2.13 on 2022-11-15 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('birth', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('fuel_dispendsed', models.PositiveIntegerField(verbose_name='Топливо выдано')),
                ('fuel_used', models.PositiveIntegerField(verbose_name='Топливо расходовано')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.employee', verbose_name='Сотрудник')),
                ('transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.transport', verbose_name='Транспорт')),
            ],
        ),
    ]
