# Generated by Django 4.1.3 on 2022-11-28 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='fuel_dispendsed',
            new_name='fuel_dispended',
        ),
    ]
