# Generated by Django 4.1.3 on 2022-11-28 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_fuel_dispendsed_report_fuel_dispended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('date',), 'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
    ]
